version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: tienda_online
    networks:
      - app-network

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./DB/tienda_online.sql:/docker-entrypoint-initdb.d/tienda_online.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tienda_online
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
